const { application } = require('express')
const express = require('express')
const routes = express.Router()
const loginRoutes = require("./loginRoutes")
const gameRoutes = require("./gameRoutes")
const homeRoutes = require("./homeRoutes")
const userRoutes = require("./userRoutes")
const registerRoutes = require("./registerRoutes")
const addBioRoutes = require("./addBioRoutes")
const loginHomeRoutes = require("./loginHomeRoutes")
const updateBioRoutes = require("./updateBioRoutes")
const deleteUserRoutes = require("./deleteUserRoutes")

routes.use("/home", homeRoutes)
routes.use("/login", loginRoutes)
routes.use("/user", userRoutes)
routes.use("/game", gameRoutes)
routes.use("/register", registerRoutes)
routes.use("/addbiodata", addBioRoutes)
routes.use("/loginhome", loginHomeRoutes)
routes.use("/updatebiodata", updateBioRoutes)
routes.use("/deleteuser", deleteUserRoutes)

module.exports = routes